
{% macro create_raw_state_us_averages_table() %}

    CREATE TABLE IF NOT EXISTS HEALTHCARE.RAW.STATE_US_AVERAGES (
        STATE_OR_NATION STRING,
        CYCLE_1_TOTAL_NUMBER_OF_HEALTH_DEFICIENCIES NUMBER,
        CYCLE_1_TOTAL_NUMBER_OF_FIRE_SAFETY_DEFICIENCIES NUMBER,
        CYCLE_2_TOTAL_NUMBER_OF_HEALTH_DEFICIENCIES NUMBER,
        CYCLE_2_TOTAL_NUMBER_OF_FIRE_SAFETY_DEFICIENCIES NUMBER,
        CYCLE_3_TOTAL_NUMBER_OF_HEALTH_DEFICIENCIES NUMBER,
        CYCLE_3_TOTAL_NUMBER_OF_FIRE_SAFETY_DEFICIENCIES NUMBER,
        AVERAGE_NUMBER_OF_RESIDENTS_PER_DAY NUMBER,
        REPORTED_NURSE_AIDE_STAFFING_HOURS_PER_RESIDENT_PER_DAY NUMBER,
        REPORTED_LPN_STAFFING_HOURS_PER_RESIDENT_PER_DAY NUMBER,
        REPORTED_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY NUMBER,
        REPORTED_LICENSED_STAFFING_HOURS_PER_RESIDENT_PER_DAY NUMBER,
        REPORTED_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY NUMBER,
        TOTAL_NUMBER_OF_NURSE_STAFF_HOURS_PER_RESIDENT_PER_DAY_ON_THE_WEEKEND NUMBER,
        REGISTERED_NURSE_HOURS_PER_RESIDENT_PER_DAY_ON_THE_WEEKEND NUMBER,
        REPORTED_PHYSICAL_THERAPIST_STAFFING_HOURS_PER_RESIDENT_PER_DAY NUMBER,
        TOTAL_NURSING_STAFF_TURNOVER NUMBER,
        REGISTERED_NURSE_TURNOVER NUMBER,
        NUMBER_OF_ADMINISTRATORS_WHO_HAVE_LEFT_THE_NURSING_HOME NUMBER,
        NURSING_CASE_MIX_INDEX NUMBER,
        CASE_MIX_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY NUMBER,
        CASE_MIX_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY NUMBER,
        CASE_MIX_WEEKEND_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY NUMBER,
        NUMBER_OF_FINES NUMBER,
        FINE_AMOUNT_IN_DOLLARS NUMBER,
        PROCESSING_DATE DATE
    );

{% endmacro %}
