
{% macro create_raw_fire_safety_deficiencies_table() %}

    CREATE TABLE IF NOT EXISTS HEALTHCARE.RAW.FIRE_SAFETY_DEFICIENCIES (
        CMS_CERTIFICATION_NUMBER STRING,
        PROVIDER_NAME STRING,
        SURVEY_DATE DATE,
        DEFICIENCY_DESCRIPTION STRING,
        DEFICIENCY_CORRECTED STRING,
        CORRECTION_DATE DATE,
        PROCESSING_DATE DATE
    );

{% endmacro %}
