
{% macro create_raw_provider_information_table() %}

    {% set table_exists_query %}
        SELECT COUNT(*) 
        FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA = 'RAW' 
          AND TABLE_NAME = 'PROVIDER_INFORMATION'
    {% endset %}

    {% set results = run_query(table_exists_query) %}
    {% if results.columns[0].values()[0] == 0 %}

        CREATE TABLE IF NOT EXISTS HEALTHCARE.RAW.PROVIDER_INFORMATION (
            CMS_CERTIFICATION_NUMBER STRING,
        PROVIDER_NAME STRING,
        PROVIDER_ADDRESS STRING,
        CITY_TOWN STRING,
        STATE STRING,
        ZIP_CODE NUMBER,
        TELEPHONE_NUMBER NUMBER,
        PROVIDER_SSA_COUNTY_CODE NUMBER,
        COUNTY_PARISH STRING,
        OWNERSHIP_TYPE STRING,
        NUMBER_OF_CERTIFIED_BEDS NUMBER,
        AVERAGE_NUMBER_OF_RESIDENTS_PER_DAY NUMBER,
        AVERAGE_NUMBER_OF_RESIDENTS_PER_DAY_FOOTNOTE NUMBER,
        PROVIDER_TYPE STRING,
        PROVIDER_RESIDES_IN_HOSPITAL STRING,
        LEGAL_BUSINESS_NAME STRING,
        DATE_FIRST_APPROVED_TO_PROVIDE_MEDICARE_AND_MEDICAID_SERVICES DATE,
        AFFILIATED_ENTITY_NAME STRING,
        AFFILIATED_ENTITY_ID NUMBER,
        CONTINUING_CARE_RETIREMENT_COMMUNITY STRING,
        SPECIAL_FOCUS_STATUS STRING,
        ABUSE_ICON STRING,
        MOST_RECENT_HEALTH_INSPECTION_MORE_THAN_2_YEARS_AGO STRING,
        PROVIDER_CHANGED_OWNERSHIP_IN_LAST_12_MONTHS STRING,
        WITH_A_RESIDENT_AND_FAMILY_COUNCIL STRING,
        AUTOMATIC_SPRINKLER_SYSTEMS_IN_ALL_REQUIRED_AREAS STRING,
        OVERALL_RATING NUMBER,
        OVERALL_RATING_FOOTNOTE NUMBER,
        HEALTH_INSPECTION_RATING NUMBER,
        HEALTH_INSPECTION_RATING_FOOTNOTE NUMBER,
        QM_RATING NUMBER,
        QM_RATING_FOOTNOTE NUMBER,
        LONG_STAY_QM_RATING NUMBER,
        LONG_STAY_QM_RATING_FOOTNOTE NUMBER,
        SHORT_STAY_QM_RATING NUMBER,
        SHORT_STAY_QM_RATING_FOOTNOTE NUMBER,
        STAFFING_RATING NUMBER,
        STAFFING_RATING_FOOTNOTE NUMBER,
        REPORTED_STAFFING_FOOTNOTE NUMBER,
        PHYSICAL_THERAPIST_STAFFING_FOOTNOTE NUMBER,
        REPORTED_NURSE_AIDE_STAFFING_HOURS_PER_RESIDENT_PER_DAY NUMBER,
        REPORTED_LPN_STAFFING_HOURS_PER_RESIDENT_PER_DAY NUMBER,
        REPORTED_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY NUMBER,
        REPORTED_LICENSED_STAFFING_HOURS_PER_RESIDENT_PER_DAY NUMBER,
        REPORTED_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY NUMBER,
        LOCATION STRING,
        LATITUDE NUMBER,
        LONGITUDE NUMBER,
        GEOCODING_FOOTNOTE NUMBER,
        PROCESSING_DATE DATE
        );

    {% else %}
        -- Table PROVIDER_INFORMATION already exists. Skipping.
    {% endif %}

{% endmacro %}
