version: 2

sources:
    - name: RAW
      database: HEALTHCARE
      schema: RAW
      tables:
        - name: FIRE_SAFETY_DEFICIENCIES
        - name: OWNERSHIP
        - name: OWNEPROVIDER_INFORMATIONRSHIP
        - name: HEALTH_DEFICIENCIES
        - name: MEDICARE_CLAIMS_QUALITY_MEASURES
        - name: PENALTIES
        - name: PROVIDER_INFORMATION
        - name: MDS_QUALITY_MEASURES
        - name: daily_nurse_staffing
        - name: FY_2024_SNF_VBP_AGGREGATE_PERFORMANCE
        - name: SNF_QUALITY_REPORTING_PROGRAM_PROVIDER_DATA
        - name: FY_2024_SNF_VBP_FACILITY_PERFORMANCE
        - name: SNF_QUALITY_REPORTING_PROGRAM_NATIONAL_DATA

models:
  - name: stg_provider_info
    description: "Staging model for Provider Information"
    columns:
      - name: cms_certification_number_ccn
        description: "CMS Certification Number as string identifier"
        tests:
          - not_null
      - name: state
        tests:
          - not_null
          - accepted_values:
              values: [AL, AK, AZ, AR, CA, CO, CT, DE, FL, GA, HI, ID, IL, IN, IA, KS, KY, LA, ME, MD, MA, MI, MN, MS, MO, MT, NE, NV, NH, NJ, NM, NY, NC, ND, OH, OK, OR, PA, RI, SC, SD, TN, TX, UT, VT, VA, WA, WV, WI, WY]
      - name: reported_total_nurse_hrs_per_resident_per_day
      - name: number_of_substantiated_complaints
      - name: processing_date
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: DATE

  - name: stg_daily_nurse_staffing
    description: "Daily nurse staffing data with RN/LPN/CNA breakdown"
    tests:
      - not_null:
          column_name: workdate
      - accepted_values:
          column_name: state
          values: [AL, AK, AZ, AR, CA, CO, CT, DE, FL, GA, HI, ID, IL, IN, IA, KS, KY, LA, ME, MD, MA, MI, MN, MS, MO, MT, NE, NV, NH, NJ, NM, NY, NC, ND, OH, OK, OR, PA, RI, SC, SD, TN, TX, UT, VT, VA, WA, WV, WI, WY]
    columns:
      - name: cms_certification_number_ccn
      - name: provider_name
      - name: city
      - name: state
      - name: county
      - name: work_date
      - name: total_nurse_hours
      - name: rn_hours
      - name: lpn_hours
      - name: aide_hours

  - name: stg_snf_vbp_performance
    description: "SNF VBP facility performance scores (readmission, staffing, etc.)"
    columns:
      - name: cms_certification_number_ccn
      - name: performance_readmission_rate
      - name: incentive_multiplier
      - name: achievement_score
      - name: improvement_score
      - name: performance_score
      - name: provider_name
      - name: city
      - name: state

  - name: stg_snf_vbp_aggregate_performance
    description: "National aggregates for SNF VBP measures"
    columns:
      - name: baseline_readmission_rate
      - name: national_readmission_rate
      - name: achievement_threshold
      - name: benchmark
      - name: number_of_snfs

  - name: stg_snf_qrp_provider_data
    description: "SNF Quality Reporting Program measures at provider level"
    columns:
      - name: cms_certification_number_ccn
      - name: measure_code
      - name: measure_score
      - name: footnote
      - name: start_date
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: DATE
      - name: end_date
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: DATE

  - name: stg_snf_qrp_national_data
    description: "SNF Quality Reporting Program measures at national level"
    columns:
      - name: cms_certification_number_ccn
      - name: measure_code
      - name: score
      - name: start_date
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: DATE
      - name: end_date
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: DATE
