{{ config(materialized='table') }}

select
  "State or Nation"                                        as state_or_nation,
  "Cycle 1 Total Number of Health Deficiencies"            as cycle_1_health_deficiencies,
  "Cycle 1 Total Number of Fire Safety Deficiencies"       as cycle_1_fire_safety_deficiencies,
  "Cycle 2 Total Number of Health Deficiencies"            as cycle_2_health_deficiencies,
  "Cycle 2 Total Number of Fire Safety Deficiencies"       as cycle_2_fire_safety_deficiencies,
  "Cycle 3 Total Number of Health Deficiencies"            as cycle_3_health_deficiencies,
  "Cycle 3 Total Number of Fire Safety Deficiencies"       as cycle_3_fire_safety_deficiencies,
  "Average Number of Residents per Day"                    as avg_residents_per_day,
  "Reported Nurse Aide Staffing Hours per Resident per Day"        as reported_nurse_aide_hours_per_resident,
  "Reported LPN Staffing Hours per Resident per Day"                as reported_lpn_hours_per_resident,
  "Reported RN Staffing Hours per Resident per Day"                 as reported_rn_hours_per_resident,
  "Reported Licensed Staffing Hours per Resident per Day"          as reported_licensed_staff_hours_per_resident,
  "Reported Total Nurse Staffing Hours per Resident per Day"       as reported_total_nurse_staff_hours_per_resident,
  "Total number of nurse staff hours per resident per day on the weekend"   as weekend_nurse_staff_hours_per_resident,
  "Registered Nurse hours per resident per day on the weekend"     as weekend_rn_hours_per_resident,
  "Reported Physical Therapist Staffing Hours per Resident Per Day" as reported_physical_therapist_hours_per_resident,
  "Total nursing staff turnover"                                 as total_nurse_staff_turnover,
  "Registered Nurse turnover"                                    as rn_turnover,
  "Number of administrators who have left the nursing home"     as admin_departures,
  "Nursing Case-Mix Index"                                       as nursing_casemix_index,
  "Case-Mix RN Staffing Hours per Resident per Day"              as casemix_rn_hours_per_resident,
  "Case-Mix Total Nurse Staffing Hours per Resident per Day"     as casemix_total_nurse_staff_hours_per_resident,
  "Case-Mix Weekend Total Nurse Staffing Hours per Resident per Day" as casemix_weekend_nurse_staff_hours_per_resident,
  "Number of Fines"                                              as num_fines,
  "Fine Amount in Dollars"                                       as fine_amount_dollars,
  "Percentage of long stay residents whose need for help with daily activities has increased" as pct_longstay_help_need_increased,
  "Percentage of long stay residents who lose too much weight"   as pct_longstay_weight_loss,
  "Percentage of low risk long stay residents who lose control of their bowels or bladder" as pct_low_risk_longstay_incontinence,
  "Percentage of long stay residents with a catheter inserted and left in their bladder" as pct_longstay_catheter_usage,
  "Percentage of long stay residents with a urinary tract infection" as pct_longstay_uti,
  "Percentage of long stay residents who have depressive symptoms" as pct_longstay_depression,
  "Percentage of long stay residents who were physically restrained" as pct_longstay_restraints,
  "Percentage of long stay residents experiencing one or more falls with major injury" as pct_longstay_falls_with_injury,
  "Percentage of long stay residents assessed and appropriately given the pneumococcal vaccine" as pct_longstay_pneumococcal_vax,
  "Percentage of long stay residents who received an antipsychotic medication" as pct_longstay_antipsychotic_med,
  "Percentage of short stay residents assessed and appropriately given the pneumococcal vaccine" as pct_shortstay_pneumococcal_vax,
  "Percentage of short stay residents who newly received an antipsychotic medication" as pct_shortstay_antipsychotic_med,
  "Percentage of long stay residents whose ability to move independently worsened" as pct_longstay_mobility_worsened,
  "Percentage of long stay residents who received an antianxiety or hypnotic medication" as pct_longstay_antianxiety_med,
  "Percentage of high risk long stay residents with pressure ulcers" as pct_highrisk_longstay_pressure_ulcers,
  "Percentage of long stay residents assessed and appropriately given the seasonal influenza vaccine" as pct_longstay_influenza_vax,
  "Percentage of short stay residents who made improvements in function" as pct_shortstay_function_improved,
  "Percentage of short stay residents who were assessed and appropriately given the seasonal influenza vaccine" as pct_shortstay_influenza_vax,
  "Percentage of short stay residents who were rehospitalized after a nursing home admission" as pct_shortstay_rehospitalized,
  "Percentage of short stay residents who had an outpatient emergency department visit" as pct_shortstay_ed_visit,
  "Number of hospitalizations per 1000 long-stay resident days" as hosp_per_1000_longstay_resident_days,
  "Number of outpatient emergency department visits per 1000 long-stay resident days" as ed_per_1000_longstay_resident_days,
  to_date("Processing Date", 'YYYY-MM-DD') as processing_date
from {{ source('RAW', 'STATE_US_AVERAGES') }}

